spring:
  datasource:
    url: jdbc:h2:mem:request_credit_system
    username: rafa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
